streams:
  - name: uvc_channel_0
    source: "/dev/video0"
    resolution: "1920x1080"
    fps: 30
  # - name: uvc_channel_1
  #   source: "/dev/video1"
  #   resolution: "1920x1080"
  #   fps: 30
  - name: uvc_channel_2
    source: "/dev/video2"
    resolution: "1920x1080"
    fps: 30
  # - name: uvc_channel_3
  #   source: "/dev/video3"
  #   resolution: "1920x1080"
  #   fps: 30
